### ISSUE TITLE
Deprecation warnings from PropEr

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#121] opened 2019-10-09 04:43 UTC
See https://github.com/proper-testing/proper/issues/204, I also see deprecation warnings when building the PropEr dependency:

```
src/proper.erl:1546: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
```

As was pointed out in the PropEr issue, this should not happen as PropEr already [uses macros](https://github.com/proper-testing/proper/blob/master/include/proper_internal.hrl#L42) to use the appropriate function. The macros are set in PropEr's rebar config and are apparently not used when compiling them from mix:

```
{erl_opts, [debug_info,
	    report_warnings, {warn_format,1}, warn_export_vars,
	    warn_obsolete_guard, warn_unused_import,
	    warn_missing_spec, warn_untyped_record,
	    {platform_define, "^19|^2", 'AT_LEAST_19'},
	    {platform_define, "^2", 'AT_LEAST_20'},
	    {platform_define, "^2[1-9]", 'AT_LEAST_21'}]}.
```

**Comment by alfert** [comment] 2019-10-09 04:47
I saw this (proper-testing/proper#204) a couple of minutes ago as well and get the same warnings. 

Any ideas about this? I have no real experience with rebar configurations.

**Comment by evnu** [comment] 2019-10-09 05:03
> Any ideas about this?

I think this has something to do how mix invokes rebar3, but I am not yet sure why. If I build PropEr manually within `deps/`, the macros are defined and no warning is written:

```
~/tools/propcheck/deps/proper(master ✗) rebar3 compile
===> Verifying dependencies...
===> Compiling proper
~/tools/propcheck/deps/proper(master ✗) ls
_build  check_escripts.sh  clean_doc.sh  clean_temp.sh  configure  COPYING  hex_metadata.config  include  Makefile  mix.exs  README.md  rebar.config  rebar.lock  src  THANKS
```

**Comment by evnu** [comment] 2019-10-09 07:29
I wonder if PropEr is even build with rebar3 when used as a mix dependency. I tried to figure out how rebar3 is called using `strace`, but there is no execve syscall for `rebar3`.

```
~/tools/propcheck(master ✗) mix deps.clean proper; mix deps.get; strace -f -e execve -s 1000 -o strace.dat mix deps.compile proper
~/tools/propcheck(master ✗) grep -q rebar strace.dat 
[1]    21032 exit 1     grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} -q rebar strace.dat
```

**Comment by evnu** [comment] 2019-10-09 07:35
So, if I change the dependencies of PropCheck` to use an explicit compile command for `PropEr`, the messages vanish:

```
  defp deps do
    [
      {:dialyxir, "~> 0.5.1", only: [:dev, :test]},
      {:coverex, "~> 1.4.15", only: :test},
      {:ex_doc, "~>0.16", only: :dev},
      {:earmark, ">= 0.2.1", only: :dev},
      {:proper, "~> 1.3", compile: "rebar3 compile"},
      {:credo, "~> 1.0.0", only: [:dev, :test], runtime: false}
    ]
  end
```

I think this might be an upstream problem after all. Shouldn't the hex package take care of knowing how to build itself?

**Comment by evnu** [comment] 2019-10-09 07:41
CC @whossname

**Comment by evnu** [comment] 2019-10-09 07:44
```
~/tools/propcheck(master ✗) grep proper mix.lock 
  "proper": {:hex, :proper, "1.3.0", "c1acd51c51da17a2fe91d7a6fc6a0c25a6a9849d8dc77093533109d1218d8457", [:make, :rebar3, :mix], [], "hexpm"},
```

Setting the compilers for proper in `mix.lock` to `rebar3` explicitly also works:

```
  "proper": {:hex, :proper, "1.3.0", "c1acd51c51da17a2fe91d7a6fc6a0c25a6a9849d8dc77093533109d1218d8457", [:rebar3], [], "hexpm"},
```

**Comment by whossname** [comment] 2019-10-09 08:17
Is it possible that this is the file that needs to change?
https://github.com/proper-testing/proper/blob/master/mix.exs

**Comment by evnu** [comment] 2019-10-09 08:19
> Is it possible that this is the file that needs to change?

I think so. I can reproduce the warnings within proper itself:

```
~/tools/proper(master ✗) mix compile
Compiling 25 files (.erl)
src/proper.erl:1593: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper.erl:1608: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_typeserver.erl:516: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_sa.erl:122: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:233: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:258: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:286: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:304: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:312: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:319: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:326: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_arith.erl:354: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_statem.erl:567: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_statem.erl:576: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_statem.erl:586: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_gen_next.erl:324: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:331: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:344: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:357: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:571: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:576: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:585: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:591: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:769: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
src/proper_gen_next.erl:773: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
Generated proper app
```

But I am not sure how this must be resolved. If we find a way, we should try to bring that upstream.

**Comment by evnu** [comment] 2019-10-09 14:50
I think the right way to solve this upstream is to get rid of `mix.exs` altogether. At least rebar3 is able to interact with hex (in the form of [rebar3_hex](https://github.com/tsloughter/rebar3_hex)), so a pure "rebar package" should be pushed to hex. But I don't know if upstream would be interested in this. According to [this comment](https://github.com/proper-testing/proper/issues/204#issuecomment-539940651), PropEr is not using rebar3 (although I can build PropEr locally with rebar3), so there might be some friction here.

**Comment by evnu** [comment] 2019-10-13 11:29
https://github.com/proper-testing/proper/commit/5f8d19daeb052164e9ecb8ee4accd70c6f0c3ec8

We need to check if we can actually build proper anymore after this change.

**Comment by kostis** [comment] 2019-10-13 11:52
> We need to check if we can actually build proper anymore after this change.

Note that this is not merged to `master` yet, and I will wait until you verify that you still can.
However, note that this just removes support for Erlang/OTP releases 18.x and prior, so, unless you still support these (old) releases, you should not have any issues.

**Comment by alfert** [comment] 2019-10-13 12:24
@kostis thanks for this. PropCheck requires currently Elixir 1.5, which is based on OTP18 and later. If we can identify the PropEr version with this PR merged, then we can release a new version of PropCheck based on Elixir 1.6 which requires OTP19 or newer. I will check now for compatibility.

**Comment by alfert** [comment] 2019-10-13 13:05
Tests are green, the warning regarding `random` are no longer there. This looks good. What we still have are these warnings: 

```
mix compile
==> proper
Compiling 25 files (.erl)
src/proper.erl:1589: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper.erl:1604: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_typeserver.erl:516: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_statem.erl:567: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_statem.erl:576: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/proper_statem.erl:586: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
Generated proper app
```

The reason is mainly the same: The `STACKTRACE` macro defined in `proper_internals.hrl` uses the configuration variable `AT_LEAST_21` defined in `rebar.config`. But this is not properly evaluated during the build as discussed above. 

We can eliminate this problem by adding to the `proper´ dependency the configuration option `manager: :rebar`. But: this does not work if I set the proper dependency to the version 1.3, downloaded from hex.

**Comment by kostis** [comment] 2019-10-13 14:31
Yes, for these warnings some other fix, perhaps involving `rebar3` needs to be made.

FYI: Note that since 4 months ago, support for 18.x and prior was dropped from the `master` branch of PropEr (https://github.com/proper-testing/proper/blob/master/rebar.config#L30), but it may be that you did not notice since it seems that compilation using `mix` is ignoring the information in `rebar.config`.

In any case, for a while now, it has been on my TODO list to release a new version of PropEr (1.4), and we should make sure both `proper` and `propcheck` work properly without warnings for that release.

**Comment by alfert** [comment] 2019-10-13 15:05
@kostis , I did not recognise the dropped support for OTP 18.x, but since we rely on PropEr 1.3 from 2018, we have not yet to deal with it :-). But good to know!  

it would be great to harmonise these issues between PropEr und PropCheck. My gut feeling is that a move towards rebar3 for PropEr (including the hex plugin for publishing instead of Mix) would also automatically result in corresponding warnings/failures when running PropCheck on OTP 18 with a dependency to PropEr 1.4. If we can help with that transformation either by cross-checking or providing a PR or something else, please let us know.

**Comment by kostis** [comment] 2019-10-15 15:16
I've submitted this PR to PropEr (https://github.com/proper-testing/proper/pull/211).

Before I merge it to master, can you verify that it works for you?
Since this is actually the first time I ever use `rebar3`, is there anything else which is needed?

**Comment by evnu** [comment] 2019-10-15 15:55
I think `mix.exs` should also be deleted, and probably the rebar plugin for hex used to publish to hex. @alfert With the following settings for the `rebar3-compile` branch, I still get deprecation warnings:

```elixir
  defp deps do
    [
      {:dialyxir, "~> 0.5.1", only: [:dev, :test]},
      {:coverex, "~> 1.4.15", only: :test},
      {:ex_doc, "~>0.16", only: :dev},
      {:earmark, ">= 0.2.1", only: :dev},
      {:proper, git: "https://github.com/proper-testing/proper", tag: "rebar3-compile"},
      {:credo, "~> 1.0.0", only: [:dev, :test], runtime: false}
    ]
  end
```

```
~/tools/propcheck(test-proper-rebar3 ✗) mix deps.clean proper; mix deps.get; mix deps.compile  
.......

==> proper
Compiling 25 files (.erl)
src/proper.erl:1589: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
...
Generated proper app
```

Now, if I use a branch without a `mix.exs` in PropEr, the warnings disappear, and rebar3 is used to compile (I checked by introducing a syntax error in PropEr):

```elixir
  defp deps do
    [
      {:dialyxir, "~> 0.5.1", only: [:dev, :test]},
      {:coverex, "~> 1.4.15", only: :test},
      {:ex_doc, "~>0.16", only: :dev},
      {:earmark, ">= 0.2.1", only: :dev},
      {:proper, git: "https://github.com/evnu/proper", tag: "rebar3-compile-without-mix"},
      {:credo, "~> 1.0.0", only: [:dev, :test], runtime: false}
    ]
  end
```

```
~/tools/propcheck(test-proper-rebar3 ✗) mix deps.get; mix deps.compile  
* Getting proper (https://github.com/evnu/proper)
....
===> Compiling proper
```

@alfert can you confirm the behaviour?

**Comment by kostis** [comment] 2019-10-15 16:22
I can delete `mix.exs` alright (I do not have any sentimental attachments to it) and substitute it with whatever infrastructure you guys suggest me (or better contribute) in order to publish to `hex.pm` and use from Elixir.

**Comment by alfert** [comment] 2019-10-16 05:35
I can confirm the behaviour and it is expected behaviour: If a mix file exists, mix will use per default. 

What worked for me is the following dependency: 

```
      {:proper, github: "proper-testing/proper" , ref: "113c569", manager: :rebar3 },
```

This did not work earlier, either the build failed or rebar was not used.  I assume that the now existing rebar3 configuration is the reason for that changed behaviour.

**Comment by kostis** [comment] 2019-10-16 06:01
OK, I will merge the branch to PropEr's `master` then and will create a new branch with `mix.exs` scheduled to be removed.  I would appreciate if you guys (or one of your users) can tell me what's needed (some `rebar3_hex` plugin/command somewhere?) for publishing to `hex.pm` and whether something is missing for using from Elixir.

**Comment by alfert** [comment] 2019-10-16 08:39
@kostis After updating the proper dependency to master (after your PR merge), the build runs without warnings, i.e. rebar3 is used. Perfect!

When we update to Proper 1.4, the warnings will be away.

**Closed by alfert** 2019-10-16 08:39 UTC
